name: first-workflow

on: push
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Hello World
       run: echo "Hello World!!!"
       
     - name: copy code
       uses: actions/checkout@v6

     - name: List repo Files
       run: ls -la
       
