name: first-workflow

on: push
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Hello World
       run: echo "Hello World!!!"
       
     - name: copy code
       uses: actions/checkout@v6

     - name: List repo Files
       run: ls -la

     - name: Create ASCII Art
       run: |
          sudo apt-get install -y figlet
          figlet "GH-200 COHACK"
          echo "--------------------------"
          figlet -f digital "GitHub Actions"
          echo "ASCII Art Generated"
     - name: Running script
       run: |
          chmod +x scripts/bash1.sh
          ./scripts/bash1.sh  
